### ISSUE TITLE
Not everywhere are types

### ISSUE THREAD

**Issue by danieldaeschle** [vibora-io/vibora#117]
You didn't add types everywhere. Is that ok, or should we create pull requests to complete it?

another thing is:
sometimes you wrote this: `def foo(param: Type=0)`
and sometimes: `def foo(param: Type  = 0)`

yes this is a little bit scrupulous but maybe you didn't saw it.

**Comment by frnkvieira** [comment]
Eventually, everything will be typed but there still a lot of work to do.
About the code standards, I'll probably add Black to the repo soon.
Thanks!
