### ISSUE TITLE
Can't install: gcc: error: vibora/parsers/parser.c: No such file or directory

### ISSUE THREAD

**Issue by Sklavit** [vibora-io/vibora#129]
**Describe the bug**
Can't install

**To Reproduce**
1. Clone repository
2. Run `python setup.py install`

**Expected behavior**
package installed.

**Screenshots**
`
running install
running bdist_egg
running egg_info
writing vibora.egg-info/PKG-INFO
writing dependency_links to vibora.egg-info/dependency_links.txt
writing requirements to vibora.egg-info/requires.txt
writing top-level names to vibora.egg-info/top_level.txt
reading manifest file 'vibora.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.rst' anywhere in distribution
warning: manifest_maker: MANIFEST.in, line 2: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

writing manifest file 'vibora.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'vibora.parsers.parser' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/torqmo/miniconda3/envs/py36sab/include/python3.6m -c vibora/parsers/parser.c -o build/temp.linux-x86_64-3.6/vibora/parsers/parser.o -O3
gcc: error: vibora/parsers/parser.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command 'gcc' failed with exit status 1
`

**Additional context**

**Comment by danieldaeschle** [comment]
You have to run `python build.py` first.

**Comment by Sklavit** [comment]
Thank you, success on Linux.

On Windows, it fails at first:
```
python build.py
Traceback (most recent call last):
  File "build.py", line 21, in <module>
    process = subprocess.run([cython] + list(pending_compilation) + ['--fast-fail'])
  File "C:\ProgramData\Miniconda3\envs\py36sab\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Miniconda3\envs\py36sab\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Miniconda3\envs\py36sab\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
But, when I run `cython _some_root_/vibora/vibora/parsers/parser.pyx _some_root_/vibora/vibora/components/components.pyx _some_root_/vibora/vibora/cache/cache.py _some_root_/vibora/vibora/protocol/cwebsocket.pyx _some_root_/vibora/vibora/protocol/cprotocol.pyx _some_root_/vibora/vibora/schemas/extensions/validator.pyx _some_root_/vibora/vibora/schemas/extensions/schemas.pyx _some_root_/vibora/vibora/schemas/extensions/fields.pyx _some_root_/vibora/vibora/responses/responses.pyx _some_root_/vibora/vibora/multipart/parser.pyx _some_root_/vibora/vibora/request/request.pyx _some_root_/vibora/vibora/router/router.py _some_root_/vibora/vibora/parsers/response.pyx _some_root_/vibora/vibora/headers/headers.py --fast-fail` it worked well.

**Comment by danieldaeschle** [comment]
Change this line
https://github.com/vibora-io/vibora/blob/17e3c5cbedcae5626805c5b07e6229fa47c71c28/build.py#L20
to `cython = 'cython'` then it works on windows.

**Comment by danieldaeschle** [comment]
@frnkvieira you shoud fix this.

**Comment by danieldaeschle** [comment]
An alternative which i found under Windows is:

`cython = os.path.join(os.path.dirname(sys.executable), 'Scripts\\cython') `

**Comment by danieldaeschle** [comment]
There isn't a cython3 command: https://github.com/cython/cython/issues/1528

**Comment by francisco-colaco** [comment]
On Fedora.28 there is a command cython3, if one installs python3-Cython.

**Comment by danieldaeschle** [comment]
whuuuat, on cython website there is no reference to this. Is cython without 3 callable too?

**Comment by danieldaeschle** [comment]
In #148 i fixed it. I think this issue can be closed. @Sklavit
