### ISSUE TITLE
Component states are not shared between different calls.

### ISSUE THREAD

**Issue by Sklavit** [vibora-io/vibora#130]
**Describe the bug**
Component states are not shared between different calls.

**To Reproduce**
1. Consider app:
`
class Statefull():
    def __init__(self):
        self.state = 0
app = Vibora()
app.components.add(Statefull())

@app.route('/'):
async def home(request: Request):
    s = app.components.get(Statefull)
    print(s.state)
    s.state = s.state + 1
   return Response()
`

2. On first request we will have in stdout: 0
3. On second request we will have in stdout: 0

**Expected behavior**
State should be shared according to documentation.

**Comment by frnkvieira** [comment]
Component states are shared between different calls but you're using a multi-processed server which means your requests are being balanced between different processes. You can drop to a single worker (`app.run(workers=1)`) to match your expectations or refactor your code to use an external database/cache to this kind of task. I could share state between the workers but that brings huge performance hits and encourage many bad practices that will fall apart when you try to scale horizontally your app.

```py
from vibora import Vibora, Response


app = Vibora()


class Counter():
    def __init__(self):
        self.value = 0


@app.route('/')
async def home():
    s = app.components.get(Counter)
    print(s.value)
    s.value = s.value + 1
    return Response(str(s.value).encode())


if __name__ == '__main__':
    app.components.add(Counter())
    app.run(workers=1)
```

I'm closing this issue but feel free to open it if you're still not satisfied.
I appreciate your feedback, thanks!

**Comment by frnkvieira** [comment]
Yes. As you can see docs are pretty primitive, there is a lot of work to do, I'll improve it over time, many thanks!
