### ISSUE TITLE
KeyError: 'index.html'

### ISSUE THREAD

**Issue by MakdosBilisim** [vibora-io/vibora#144]
If install 0.0.7 version with Github clone template files are not found in templates folder or in  other folders.

**Comment by danieldaeschle** [comment]
Please post your code and the stack trace.

**Comment by MakdosBilisim** [comment]
Hi again;

I get the following error when starting setup.

python3.6 setup.py build:
..
x86_64-linux-gnu-gcc: error: vibora/parsers/parser.c: Böyle bir dosya ya da dizin yok
**x86_64-linux-gnu-gcc: fatal error: no input files**
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1


I am editing as below to correct this error.
nano +20 build.py
..
..
#cython = os.path.join(os.path.dirname(sys.executable), 'cython')
cython="cython"


And I'm testing again.

python3.6 build.py
..
..
**Build process completed successfully.**



python3.6 setup.py install
..
..
**Finished processing dependencies for vibora==0.0.7**




nano samples/templates.py 
debug=True



python3.6 samples/templates.py 
# Vibora (0.0.7) # http://0.0.0.0:8000
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/vibora-0.0.7-py3.6-linux-x86_64.egg/vibora/templates/engine.py", line 84, in render
    template = self.templates[name]
**KeyError: 'index.html'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vibora/protocol/cprotocol.pyx", line 144, in vibora.protocol.cprotocol.Connection.handle_request
    response = await route.call_handler(request, self.components)
  File "samples/templates.py", line 11, in home
    return await app.render('index.html', teste=t)
  File "/usr/local/lib/python3.6/dist-packages/vibora-0.0.7-py3.6-linux-x86_64.egg/vibora/blueprints.py", line 137, in render
    content = await self.app.template_engine.render(template_name, **template_vars)
  File "/usr/local/lib/python3.6/dist-packages/vibora-0.0.7-py3.6-linux-x86_64.egg/vibora/templates/engine.py", line 100, in render
    raise TemplateNotFound(name)
vibora.templates.exceptions.TemplateNotFound: index.html

**Comment by danieldaeschle** [comment]
You have to run `python build.py` first before you run `setup.py`.

**Comment by MakdosBilisim** [comment]
It's ok. 

I am running sample/templates.py and give me error.

**Comment by MakdosBilisim** [comment]
Ok. Problem solved.

We have to write templates_dirs and static folder's dict.

app = Vibora(
    **template_dirs**=['/home/musluyuksektepe/PycharmProjects/vibora_proje/templates'],
    **static**=StaticHandler(paths=['/home/musluyuksektepe/PycharmProjects/vibora_proje/static'])
)


sample app.py
from vibora import Vibora
from vibora.static import StaticHandler

app = Vibora(
    template_dirs=['/home/musluyuksektepe/PycharmProjects/vibora_proje/templates'],
    static=StaticHandler(paths=['/home/musluyuksektepe/PycharmProjects/vibora_proje/static'])
)

t = [x for x in range(0, 5)]


@app.route('/')
async def home():
    return await app.render('index.html', teste=t)


if __name__ == '__main__':
    app.run(debug=True, port=8000)
