### ISSUE TITLE
Unable to build vibora extension from source because cython path is misconfigured

### ISSUE THREAD

**Issue by pcdinh** [vibora-io/vibora#159]
**Describe the bug**

After `git clone` vibora, I tried to run `python3 build.py`. However, it didn't work

**To Reproduce**

1. Install `cython` in Ubuntu 18: `sudo pip3 install cython`
2. Clone vibora: `git clone https://github.com/vibora-io/vibora.git`
3. Build extension

`python3 build.py`

Error occurs
```
Traceback (most recent call last):
  File "build.py", line 21, in <module>
    process = subprocess.run([cython] + list(pending_compilation) + ['--fast-fail'])
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/cython': '/usr/bin/cython'
```

Here is my `cython` path

```
~/vibora$ which cython
/usr/local/bin/cython
```

**Expected behavior**
`python3 build.py` should work instead of throwing an exception

**Comment by danieldaeschle** [comment]
https://github.com/vibora-io/vibora/issues/145

Please close.

**Comment by pcdinh** [comment]
Closed because of duplicated report. Thank @danieldaeschle
