### ISSUE TITLE
Add a Chatroom for the community 

### ISSUE THREAD

**Issue by rishavs** [vibora-io/vibora#163]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to engage with the community other than Github issues and it is not the right place for non-issue centric discussion.

**Describe the solution you'd like**
Adding a chatroom on any of the following platforms;

- Gitter
- Slack
- Discourse

this thread can also serve as a discussion point for the pros/cons of each platform.

In the readme.md and website a section for _community_ should be detailed where the link to the chatroom is provided.

Furthermore, whichever option was chosen as the platform should also have its badge added to the top of the Readme.md.

All of these would ensure that the community has a real time communication channel with each other and that this channel is prominently displayed for the benefit of new users.

**Comment by frnkvieira** [comment]
Slack: https://join.slack.com/t/vibora-io/shared_invite/enQtNDAxMTQ4NDc5NDYzLTA2YTdmNmM0YmY4ZTY0Y2JjZjc0ODgwMmJjY2I0MmVkODFiYzc4YjM0NGMyOTkxMjZlNTliZDU1ZmFhYWZmNjU
I'll set up badges and everything when I get home. Thanks!

**Comment by rishavs** [comment]
From what I remember, gitter has the issue with searching of historical posts. So people will not be able to search for issues which have previously been answered.

**Comment by danieldaeschle** [comment]
I just don't like that it's blocked in my company xD
