### ISSUE TITLE
How to use Sessions?

### ISSUE THREAD

**Issue by s0kil** [vibora-io/vibora#187]
Does Vibora support sessions yet?
If so, an example would be helpful.
Thanks

**Comment by btegs** [comment]
How familiar are you with Redis? In the past I have leveraged Redis to store session related data and has worked well. Oh and setting an EXPIRES on the key is also helpful if you want a session to end at a certain time and have the browser and/or web app check.

**Comment by DanielSokil** [comment]
Found this https://github.com/vibora-io/vibora/tree/master/samples/sessions

**Comment by Dexus77** [comment]
DanielSokil 

Do you use a session with Redis?
I can not find the AsyncRedis class anywhere
ImportError: cannot import name 'AsyncRedis' from 'vibora.sessions'

**Comment by DanielSokil** [comment]
@Dexus77 I never got this to work either.
