### ISSUE TITLE
Please, use mingw or TMD GCC as much as you can, not vival studio.

### ISSUE THREAD

**Issue by AlphaFase** [vibora-io/vibora#194]
**Is your feature request related to a problem? Please describe.**
Please, don't use vitual Studio Complie tools.

**Describe the solution you'd like**
Set the environment variable XXX_COMPLIE _ TOOLS to call the GCC compiler(mingw or TDM GCC)
Eg:
Set XXX_COMPLIE _ TOOLS = D: / tdm_gcc / bin

**Additional context**
In order to compile a 1MB program, I need to install a 100,00000G byte of the voltal studio. Don't joke. Everyone is so busy and the bandwidth is not cheap

**Comment by danieldaeschle** [comment]
And additionally VS isn't really working then...
