### ISSUE TITLE
Error when importing Vibora

### ISSUE THREAD

**Issue by Dyleee** [vibora-io/vibora#218]
After installing Vibora, it seems unusable with this Error when trying to import it

![image](https://user-images.githubusercontent.com/36546002/48678045-34db6400-eb7e-11e8-93d0-b8bca3fd5c3a.png)

**Comment by hamurai** [comment]
[Python3.7 included](https://docs.python.org/3/whatsnew/3.7.html) backwards incompatible syntax changes:
- async and await are now reserved keywords.

Assuming the `WIP 3.7` updates will eventually address these incompatibilities.

**Comment by Dyleee** [comment]
Okay, Thank you
