### ISSUE TITLE
I hope the author can continue to improve this project.

### ISSUE THREAD

**Issue by VcrTing** [vibora-io/vibora#231]
I hope the author can continue to improve this project. 

The author has disappeared for several months. I like this project very much, but I feel uneasy to see that it has not been updated for a long time.

If you plan to continue improving in the future, expect to be more restful～

**Comment by yxxhero** [comment]
me too, are you a chinese gril?

**Comment by frnkvieira** [comment]
Hi @VcrTing 
It was never my intention to disappear but life has been **really** tough in the last months.
The good news is that I've been re-wroting Vibora since then and finally things are settling down in my life.

**Comment by VcrTing** [comment]
No matter at any time, a great man will not give up easily, I hope you can overcome difficulties, more and more brave, wish you and your vibor can be better and better ~

**Comment by VcrTing** [comment]
> me too, are you a chinese gril?

yes.
