### ISSUE TITLE
When will the documentation be complete?

### ISSUE THREAD

**Issue by blueray453** [vibora-io/vibora#258]
Many documentation pages are blank or says WIP... or Under construction

Ex. 

https://docs.vibora.io/initial-2/session
https://docs.vibora.io/engine/performance
https://docs.vibora.io/extensions

When will we get a complete documentation?

**Comment by prostomarkeloff** [comment]
Probably never ;) In this moment vibora completely rewriting. Will wait new docs.

**Comment by blueray453** [comment]
Where can I find details about vebora release milestones, and upcoming features.

**Comment by prostomarkeloff** [comment]
In slack.
