### ISSUE TITLE
Is it possible to use multiple CPU cores?

### ISSUE THREAD

**Issue by asfaltboy** [vibora-io/vibora#27]
Since [the official docs][1] recommend placing Vibora without a proxy or load balancer, I'm curious how Vibora is meant to be used in a multi-core machine to best utilize available resources?

[1]: https://docs.vibora.io/docs/deployment

**Comment by almarklein** [comment]
I was wondering this as well. I have been playing with Nginx Unit + a Python WSGI script, but using Vibora would be so much easier ...

**Comment by frnkvieira** [comment]
Vibora is multi-processed by default which means it'll make use of all your CPU cores. You can configure how many workers do you want in the "app.run(workers=10)" method but beware that the default is a pretty good one.

**Comment by almarklein** [comment]
Out of curiosity, how does the main process communicate with its workers? Sockets? Pipes?

**Comment by jediborre** [comment]
how can I run in production a vibora Script then?

**Comment by danieldaeschle** [comment]
Just use the `app.run()`

**Comment by jediborre** [comment]
For example, I have my script.py then in my ubuntu y Type

python3.6 script.py &

then I can close my ssh session and my script will live forever?

**Comment by danieldaeschle** [comment]
Maybe you have to use `nohup` or just something that runs it in background.

My suggestion is to use docker.

**Comment by jediborre** [comment]
Do you have an example how can I run with docker :)

**Comment by danieldaeschle** [comment]
there are so many examples in the web...

https://runnable.com/docker/python/dockerize-your-python-application
