### ISSUE TITLE
Unable to locate template with render template

### ISSUE THREAD

**Issue by Jarmahent** [vibora-io/vibora#39]
I used the sample code with a simple folder structure. 1 folder with 2 files in it `app.py` and `index.html`

I got the sample code from this repo but Ill show it anyways:
```python
from vibora import Vibora



app = Vibora()

t = [x for x in range(0, 5)]


@app.route('/')
async def home():
    return await app.render('index.html', teste=t)
```

Whenever I try to go to that route on the server I get: 
```traceback
Traceback (most recent call last):
  File "vibora/protocol/cprotocol.pyx", line 152, in vibora.protocol.cprotocol.Connection.handle_request
  File "/app/server/__init__.py", line 11, in home
    return await app.render('./index.html', teste=t)
  File "/data/lib/python3.6/site-packages/vibora/blueprints.py", line 131, in render
    content = await self.app.template_engine.render(template_name, **template_vars)
  File "/data/lib/python3.6/site-packages/vibora/templates/engine.py", line 100, in render
    raise TemplateNotFound(name)
vibora.templates.exceptions.TemplateNotFound: ./index.html
```

Ive tried at least 10 different path configs such as `./index.html`, I tried putting it in a templates folder and referencing it from there. I also tried to do `os.getcwd()` with no luck either.

**Comment by dukkee** [comment]
@Jarmahent move `index.html` to `templates` folder. As I see, now we can't change this path.

**Comment by Jarmahent** [comment]
I tried adding a template directory and then did `app.render('index.html')` but no look but it looks like doing: `app = Vibora(template_dirs=['.'])`.

**Comment by Jarmahent** [comment]
Apparently it was a personal error, I used flask so much that  while initiating the Vibora class i thought you had to add `__name__` to `app = Vibora()`. Which caused there error.
