### ISSUE TITLE
Is there any Benchmark against "nodejs" or "go"?

### ISSUE THREAD

**Issue by rebootcode** [vibora-io/vibora#41]
Please add benchmark against "nodejs" and "golang"

**Comment by RanchoCooper** [comment]
Approved！

**Comment by AndrewBurdyug** [comment]
would be very exciting to see such benchmark

**Comment by vsxen** [comment]
which web framework？NodeJS(express, koa)    golang(gin, beego)?

**Comment by rebootcode** [comment]
NodeJS -> ExpressJS
Golang -> "golang iris" or "gramework" framework

**Comment by guppythegod** [comment]
That would be awesome to see!

**Comment by Marlysson** [comment]
And about Elixir using Phoenix ? Seem it is a fast language as your framework..

**Comment by grigi** [comment]
I think we should rather help Frank get this framework in a good working condition first.

He did state that he isn't interested in going after just speed, but something that is:
Correctness > Performance > Ease of use > Maintainability
(Which I think is a very sane order of priorities)

Also, benchmarking between different frameworks are incredibly difficult to make it representative.
Unrepresentative benchmarking is a lie.

**Comment by GMLudo** [comment]
You should participate in this benchmark: https://www.techempower.com/benchmarks/#section=code

**Comment by waghanza** [comment]
or https://github.com/tbrand/which_is_the_fastest

DISCLAIMER : I am the main **maintainer**, not the **author**

@greed2411 is introducing `vibora` in https://github.com/tbrand/which_is_the_fastest/pull/285

**Comment by danieldaeschle** [comment]
@rebootcode 
Golang -> standard library is a better choice

**Comment by waghanza** [comment]
`vibora` has been integrated to  https://github.com/tbrand/which_is_the_fastest

**Comment by rebootcode** [comment]
Above reply solves the issue - https://github.com/vibora-io/vibora/issues/41#issuecomment-402719538
