### ISSUE TITLE
Rename vibora suggest

### ISSUE THREAD

**Issue by RanchoCooper** [vibora-io/vibora#45]
**Additional suggest**
Such a **sexy** Python web framework should be accompanied by a **internationalized**, **hotter** 
 name

For example, `Tornado`, `Flask`, `Django`, These names are all catchy.

**Comment by AndrewBurdyug** [comment]
yeah and maybe more friendly than snake which can deathly bite :)

**Comment by rafaelcapucho** [comment]
Vibora is cool, don't worry

**Comment by fpSpindola** [comment]
@AndrewBurdyug Python Snakes kills by constriction. Why is that better than a bite?

**Comment by frnkvieira** [comment]
I appreciate your efforts but this thread is not going anywhere.

**Comment by DanielSokil** [comment]
Vibora, lovely.
