### ISSUE TITLE
Error is running the basic program

### ISSUE THREAD

**Issue by omkarnathsingh** [vibora-io/vibora#80]
>>> from vibora import JsonResponse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'JsonResponse'

I was running https://docs.vibora.io/docs/ first program in it. Help please, thanks.

**Comment by dukkee** [comment]
> from vibora.responses import JsonResponse

@omkarnathsingh

**Comment by omkarnathsingh** [comment]
https://github.com/vibora-io/vibora/pull/81 
Yeah, I got that and have raised a PR for correcting the docs, please look into it. Thanks.
