### ISSUE TITLE
Docs page link is broken

### ISSUE THREAD

**Issue by vsoch** [vibora-io/vibora#88]
**Describe the bug**
The "getting started" goes to [https://docs.vibora.io/docs/](https://docs.vibora.io/docs/) but it should go to [https://docs.vibora.io/](https://docs.vibora.io/)

**To Reproduce**
1. Go to https://docs.vibora.io/docs
2. 404!
3. Cry softly
4. Make a snack
5. Feel better

**Expected behavior**
1. Click on "Getting Started"
2. Get taken to https://docs.vibora.io/
3. Enlghtenment

**Screenshots**

![image](https://user-images.githubusercontent.com/814322/41996626-596b05e0-7a0a-11e8-9a2a-21f3c65b36fc.png)

**Additional context**
Chrome, Ubuntu 16.04, but it doesn't matter. It's a broken link :)

**Comment by frnkvieira** [comment]
Fixed. Many thanks!
