### ISSUE TITLE
How is vibora so fast?

### ISSUE THREAD

**Issue by ivegotasthma** [vibora-io/vibora#92]
Hello,

I'm comparing the performance between vibora and [iris](https://github.com/kataras/iris#installation) and I'm surprised by the margin python leads with. What's the deal with that?

**Comment by frnkvieira** [comment]
I'm not sure how you are doing this comparison but Vibora performance comes from Cython. Go is faster than Python by a good margin so you can be sure there'll be Go frameworks faster than Vibora. (https://github.com/valyala/fasthttp this one for example)

**Comment by gpkc** [comment]
I would not say that Go is faster than Cython, though. It is probably comparable.
Can you also share how you are doing the comparison?

**Comment by rfyiamcool** [comment]
@gpkc  see issue  #108 

```
Performance is thanks to Cython + Uvloop + C HTTP parser.
(https://docs.vibora.io/faq#where-the-performance-comes-from)
Feel free to open this issue if you have more doubts, thanks!
```

**Comment by gpkc** [comment]
@rfyiamcool I don't see how this relates to my comment? I'm aware of where the performance comes from. I just meant that Go should not necessarily be considered faster than Cython, and that I was also curious as how OP performed his tests.

**Comment by ivegotasthma** [comment]
@gpkc they're not my benchmarks but from the iris project. https://github.com/kataras/iris#installation

**Comment by gpkc** [comment]
OK but you must make sure the comparison is fair. You should probably run the benchmarks on the same machine, and make sure the services are equivalent.

**Comment by xuanchengli** [comment]
@frnkvieira Are u use the build-in server of vibora for the performance testing? Because the docs show me Gunicorn/uWSGI is not a good way to deploy vibora service. If you not use build-in server, and how to integrate and deploy vibora with other web server (such as nginx and apache)?

**Comment by xuanchengli** [comment]
@danieldaeschle Thanks! I will try to test it on my VPS.
