### ISSUE TITLE
Why not gunicorn ?

### ISSUE THREAD

**Issue by waghanza** [vibora-io/vibora#93]
Hi,

We are introducing `vibora` to `which_is_the_fastest`, https://github.com/tbrand/which_is_the_fastest/issues/282

I can read that the recommendation is not to run on `gunicorn`, https://docs.vibora.io/deployment, as `vibora` is `async`.

However `gunicorn` **can** run on `async`, http://docs.gunicorn.org/en/stable/design.html#asyncio-workers.

Regards,

**Comment by frnkvieira** [comment]
Performance. 
Introducing Gunicorn means I lose the ability to do a lot of micro-optimizations.
It was never my intention to say that Gunicorn lacks async support, I'll update the docs to make myself clear... If you need any help, feel free to ask me :)

**Comment by waghanza** [comment]
ok. I'll try without `gunicorn`, it **could** be easier for my configurations (since I am using `gunicorn` for `flask` / `tornado` ...)
