### ISSUE TITLE
Why blueprints?

### ISSUE THREAD

**Issue by danieldaeschle** [vibora-io/vibora#97]
I wonder why this framework is using "blueprints" like Flask. I didn't know what blueprints means. In my opinion it is something like a template. But in this case it doesn't mean template.

My suggestion is to call it something like `Router` or `Namespace`.

What do you think?

**Comment by stop5** [comment]
A Blueprint is an way to modularize apps. Your suggestion Router is already used for real Routers, Blueprints doesn't route anything. Namespace is in my opinion a bit too indifferent. The Term comes from the architecture https://en.wikipedia.org/wiki/Blueprint.

**Comment by frnkvieira** [comment]
Although I confess that I dislike this name too I think it's a very wide-spread concept in the Python community thanks to Flask so I don't think we gonna find a better replacement.
