### ISSUE TITLE
suggestion: use dict.setdefault() and/or defaultdict in router.py

### ISSUE THREAD

**Issue by ariebovenberg** [vibora-io/vibora#99]
A very minor issue: In `router.py`, there is a lot of code that looks like this:

```python
if method not in routes:
    routes[method] = []
routes[method].append(route)
```

python's `dict` has a nice `setdefault()` method for this pattern.

The example above becomes:

```python
routes.setdefault(method, []).append(route)
```

see the [docs](https://docs.python.org/3.7/library/stdtypes.html#dict.setdefault) for more info.

If retrieving values like this is the norm, it's probably best to use `defaultdict`:

```python
routes = defaultdict(list)
# ...
routes[method].append(route)
```

see the [docs](https://docs.python.org/3.7/library/collections.html#collections.defaultdict).

**Comment by frnkvieira** [comment]
Hi @ariebovenberg,
`defaultdict` is not as optimized as a vanilla `dict` in Cython so I deliberately skip it everywhere.
But I was not aware of the `setdefault` method (because I usually rely on defaultdict haha) so I really appreciate your tip and will refactor the code. Many thanks!

**Comment by frnkvieira** [comment]
Already started the refactoring, feel free to open this issue if you have more tips :)
